title = "Dotfiles gitleaks config"

[extend]
useDefault = true

[allowlist]
paths = [
  '''.*Vencord.*''',
  '''.*vesktop.*''',
  '''.*WindowsTerminal.*settings\.json''',
  '''^other_config/stylus/stylus\.json$''',
  '''^dot_config/stylus/stylus\.json$''',
  '''^stylus-old\.json$''',
]
