
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_file = ~/.config/hypr/keymap.xkb
    kb_layout = us
    kb_variant = intl
    # kb_options = compose:ralt
    
    follow_mouse = 1
    sensitivity = 0
    # force_no_accel = 1      # Forzar nula aceleración
    accel_profile = flat      # Raw input
    numlock_by_default = true
 
    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad   
    touchpad {
        natural_scroll = no
    }
}

device {
    name = sony-interactive-entertainment-dualsense-wireless-controller-touchpad
    #enabled = false
}

# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
}

# for window shallow similar to devour
misc {
    # enable_swallow = true
    # swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
}

# Don't show update on first launch
ecosystem {
  # no_update_news = true
}


# // █▀ █▀█ █▀▀ █▀▀ █ ▄▀█ █░░
# // ▄█ █▀▀ ██▄ █▄▄ █ █▀█ █▄▄

decoration {
    #dim_special = 0.3
    #active_opacity = 0.95
    #inactive_opacity = 0.85
}


# // █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# // █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

# ? Assuming exec-once are launched in order as declared here

# Core
$start.SWAYOSD=hyde-shell app -t service swayosd-server
exec-once = $start.SWAYOSD
