[Rainmeter]

BackgroundMode=2
SolidColor=0,0,0,1
DynamicWindowSize=1
AccurateText=1
DynamicVariables=1

MouseScrollUpAction=[!SetVariable Scale "(#Scale#+#ScrollMouseIncrement#)"][!WriteKeyValue Variables Scale "(#Scale#+#ScrollMouseIncrement#)"][!Refresh] 
MouseScrollDownAction=[!SetVariable Scale "(#Scale#-#ScrollMouseIncrement# < 0.1 ? 0.1 : #Scale#-#ScrollMouseIncrement#)"][!WriteKeyValue Variables Scale "(#Scale#-#ScrollMouseIncrement# < 0.1 ? 0.1 : #Scale#-#ScrollMouseIncrement#)"][!Refresh]


[Metadata]
Name=Trashy Light
Author=niivu (adni18 credits for the resizing script , eldog-02 for the bin prompt)


; ----------------------------------------- Inclusions

[Variables]

Radius=16
Stroke=0
FontName=Mulish Medium
BG=EFF1F5
FG=4C4F69
BORDER=DCE0E8
Color1=209FB5
Scale=1.1
ScrollMouseIncrement=0.2
SkinWidth=180
SkinHeight=80

; ---------------------------------------- Background

[mBackShape]
Meter=Shape
Shape=Rectangle 0,0,(180*#Scale#),(80*#Scale#),#Radius# | Fillcolor #BG# | Strokewidth #Stroke# | StrokeColor #BORDER#

; ----------------------------------------- Measures

[MeasureBinNum]
Measure=Plugin
Plugin =RecycleManager
RecycleType=Count

[MeasureBinSize]
Measure=Plugin
Plugin=RecycleManager
RecycleType=SIZE

; ----------------------------------------- Recycle String

[MeterCount]
Meter=STRING
MeasureName=MeasureBinNum
FontColor=#FG#
FontSize=(12*#Scale#)
FontFace=#FontName#
X=(130*#Scale#)
Y=(30*#Scale#)
W=((#SkinWidth#))
H=((#SkinHeight#))
StringAlign=CenterCenter
Postfix=" Items"
Text=%1
AntiAlias=1
DynamicVariables=1

[MeterSize]
Meter=STRING
MeasureName=MeasureBinSize
FontColor=#Color1#
FontSize=(14*#Scale#)
FontFace=#FontName#
Text=%1
Postfix="B"
AutoScale=1
AntiAlias=1
NumOfDecimals=0
X=(130*#Scale#)
Y=(50*#Scale#)
W=((#SkinWidth#-10))
H=((#SkinHeight#-10))
StringAlign=CenterCenter
AntiAlias=1
DynamicVariables=1

; ----------------------------------------- Recycle Icon

[MeterBinEmpty]
Meter=Image
ImageName=#@#\Images\Cat.png
X=(15*#Scale#)
Y=(15*#Scale#)
W=(48*#Scale#)
AntiAlias=1
DynamicVariables=1
Hidden=0
LeftMouseUpAction=[!ShowMeterGroup BinPrompt][!HideMeter MeterBinEmpty][!UpdateMeter #CurrentSection#]

[MeterBinFull]
Meter=Image
ImageName=#@#\Images\Cat Full.png
X=(15*#Scale#)
Y=(15*#Scale#)
W=(48*#Scale#)
AntiAlias=1
DynamicVariables=1
Hidden=1
LeftMouseUpAction=[!Redraw][!ShowMeterGroup BinPrompt][!HideMeter MeterBinFull][!UpdateMeter #CurrentSection#]

; ----------BIN Action

[BinAction]
Measure=Calc
Formula=MeasureBinSize
IfAboveAction=!execute [!HideMeter MeterBinEmpty][!ShowMeter MeterBinFull][!Update]
IfAboveValue=0
IfEqualAction=!execute [!HideMeter MeterBinFull][!ShowMeter MeterBinEmpty][!Update]
IfEqualValue=0

; ----------------------------------------- Recycle Bin Prompt

[PromptBG]
Meter=Shape
Group=BinPrompt
Shape=Rectangle 0,0,(180*#Scale#),(80*#Scale#),#Radius# | Fillcolor #BG# | Strokewidth #Stroke# | StrokeColor #BORDER#
UpdateDivider=-1
Hidden       =1

[Prompt]

Meter=String
MeterStyle =BinPrompt
AntiAlias=1
FontColor=#FG#
FontSize=(12*#Scale#)
FontFace=#FontName#
Text =Empty Recycle Bin?
X=(90*#Scale#)
Y=20
MouseOverAction =
MouseLeaveAction=

[Empty]
Meter=String
MeterStyle=BinPrompt
AntiAlias=1
X=(45*#Scale#)
Y=(45*#Scale#)

LeftMouseUpAction=[!CommandMeasure MeasureBinNum "EmptyBinSilent"][!HideMeterGroup BinPrompt][!ShowMeter MeterBinEmpty][!Update]

[Open]
Meter=String
MeterStyle=BinPrompt
AntiAlias=1
X=(140*#Scale#)
Y=(45*#Scale#)

LeftMouseUpAction=[shell:RecycleBinFolder][!HideMeterGroup BinPrompt][!ShowMeter MeterBinFull][!Update]

; ----------------------------------------- Recycle Bin

[BinPrompt]
InlineSetting =Face | #fontname#
InlineSetting2=Size | (12*#Scale#)
InlineSetting3=Color| #FG#
UpdateDivider =-1
StringAlign=CenterCenter
Antialias  =1
Hidden     =1
Group      =BinPrompt
Text       =#CurrentSection#
Y=r
W=30
H=(9*#Scale#)

; ----------------------------------------- Drag and Drop

[DragNDrop]
Measure=Plugin
Plugin =Drag&Drop
Action =Delete
Bounds =0,0,100,100
