# Kanagawa Dragon palette

theme[main_bg]="#0d0c0c"
theme[main_fg]="#c5c9c5"
theme[title]="#c5c9c5"
theme[hi_fg]="#8ba4b0"
theme[selected_bg]="#282727"
theme[selected_fg]="#8ba4b0"
theme[inactive_fg]="#625e5a"
theme[graph_text]="#c4b28a"
theme[meter_bg]="#393836"
theme[proc_misc]="#b6927b"

theme[cpu_box]="#8ba4b0"
theme[mem_box]="#8a9a7b"
theme[net_box]="#c4746e"
theme[proc_box]="#8992a7"
theme[div_line]="#625e5a"

theme[temp_start]="#8a9a7b"
theme[temp_mid]="#c4b28a"
theme[temp_end]="#c4746e"

theme[cpu_start]="#8ba4b0"
theme[cpu_mid]="#8992a7"
theme[cpu_end]="#b6927b"

theme[free_start]="#8a9a7b"
theme[free_mid]="#8ba4b0"
theme[free_end]="#8992a7"

theme[cached_start]="#8ba4b0"
theme[cached_mid]="#8992a7"
theme[cached_end]="#c4b28a"

theme[available_start]="#b6927b"
theme[available_mid]="#c4746e"
theme[available_end]="#c4746e"

theme[used_start]="#8a9a7b"
theme[used_mid]="#8ba4b0"
theme[used_end]="#8992a7"

theme[download_start]="#8ba4b0"
theme[download_mid]="#8992a7"
theme[download_end]="#b6927b"

theme[upload_start]="#8a9a7b"
theme[upload_mid]="#8ba4b0"
theme[upload_end]="#8992a7"

theme[process_start]="#8ba4b0"
theme[process_mid]="#8992a7"
theme[process_end]="#c4b28a"
