# Kanagawa Dragon palette

[colors.primary]
background = "#0d0c0c"
foreground = "#c5c9c5"
dim_foreground = "#625e5a"
bright_foreground = "#c5c9c5"

[colors.cursor]
text = "#0d0c0c"
cursor = "#c5c9c5"

[colors.vi_mode_cursor]
text = "#0d0c0c"
cursor = "#8ba4b0"

[colors.search.matches]
foreground = "#0d0c0c"
background = "#a6a69c"

[colors.search.focused_match]
foreground = "#0d0c0c"
background = "#8a9a7b"

[colors.footer_bar]
foreground = "#0d0c0c"
background = "#a6a69c"

[colors.hints.start]
foreground = "#0d0c0c"
background = "#c4b28a"

[colors.hints.end]
foreground = "#0d0c0c"
background = "#a6a69c"

[colors.selection]
text = "#c5c9c5"
background = "#393836"

[colors.normal]
black = "#0d0c0c"
red = "#c4746e"
green = "#8a9a7b"
yellow = "#c4b28a"
blue = "#8ba4b0"
magenta = "#a292a3"
cyan = "#8ea4a2"
white = "#a6a69c"

[colors.bright]
black = "#625e5a"
red = "#c4746e"
green = "#87a987"
yellow = "#c4b28a"
blue = "#7fb4ca"
magenta = "#8992a7"
cyan = "#8ea4a2"
white = "#c5c9c5"

[[colors.indexed_colors]]
index = 16
color = "#b6927b"

[[colors.indexed_colors]]
index = 17
color = "#a292a3"
