[Rainmeter]
Update=1000
AccurateText=1

[Metadata]
Name=Terminal
Author=Dule
Version=1.0
License=Creative Commons Attribution - Non - Commercial - Share Alike 3.0

[Variables]
@include=#@#styles.inc

; -------------------------------------------------------------------
; METERS
; -------------------------------------------------------------------

[BGTerminal]
Meter=Shape
Shape=Rectangle 0,0,80,80,#Radius# | Fillcolor #Peach# | Strokewidth 0

[MeterTerminal]
Meter=String
X=40
Y=40
W=50
H=50
StringAlign=CenterCenter
FontColor=#Gray0#
FontFace=#fontname#
FontWeight=700
FontSize=26
AntiAlias=1
Text=>_
LeftMouseDownAction=["alacritty.exe"]
ToolTipText=Terminal
