"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:orange)\
$os\
$username\
[](bg:yellow fg:orange)\
$directory\
[](fg:yellow bg:green)\
$git_branch\
$git_status\
[](fg:green bg:cyan)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:cyan bg:blue)\
$docker_context\
$conda\
$pixi\
[](fg:blue bg:black6)\
$cmd_duration\
$time\
[ ](fg:black6)"""

add_newline = false
palette = 'kanagawa_dragon'

[username]
show_always = true
style_user = "bg:orange fg:black"
style_root = "bg:orange fg:black"
format = '[ $user ]($style)'
disabled = false

[os]
disabled = false
style = "bg:orange fg:black"
format = '[ $symbol]($style)'

[os.symbols]
Windows = ""
Arch = "󰣇"
Linux = "󰌽"
Ubuntu = "󰕈"
Fedora = "󰣛"
Debian = "󰣚"
Macos = "󰀵"

[directory]
style = "bg:yellow fg:black"
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:green fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:green fg:black"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[bun]
symbol = ""
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version)(\(#$virtualenv\)) ]($style)'

[docker_context]
symbol = " "
style = "bg:blue fg:black"
format = '[ $symbol $context ]($style)'

[conda]
symbol = " "
style = "bg:blue fg:black"
format = '[ $symbol$environment ]($style)'

[pixi]
style = "bg:blue fg:black"
format = '[ $symbol$environment ]($style)'

[cmd_duration]
min_time = 2000
style = "bg:black6 fg:text"
format = '[  $duration ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:black6 fg:text"
format = '[  $time ]($style)'

[character]
disabled = true

[palettes.kanagawa_dragon]
background = "#0d0c0c"
black = "#0d0c0c"
black1 = "#12120f"
black2 = "#181616"
black3 = "#1d1c19"
black4 = "#282727"
black5 = "#393836"
black6 = "#625e5a"
base = "#1d1c19"
surface = "#282727"
surface_alt = "#393836"
border = "#625e5a"
text = "#c5c9c5"
muted = "#a6a69c"
blue = "#8ba4b0"
cyan = "#8ea4a2"
green = "#8a9a7b"
yellow = "#c4b28a"
orange = "#b6927b"
red = "#c4746e"
violet = "#8992a7"
pink = "#a292a3"
